export const about = {
  badge: "MS HCI/d Capstone Project 2026",
  headline: "Strategic Product Designer with experience spanning across travel, fintech, real estate, consumer, productivity, and enterprise CRMs",
  paragraphs: [
    "I started in computer science, studying AI and machine learning, and somewhere along the way I realized I was always more interested in the gap between what a system could do and what a person actually needed from it. That gap is where I ended up building my career.",
    "I moved into UX and product design after my engineering degree because design is where both sides of my background actually connect. The technical foundation means I can read code, build functional prototypes using tools like Cursor, Lovable, and Framer, have real conversations with engineers about constraints, and understand what I am asking for when I spec an interaction. It also means when I design for AI products I am not guessing at how the system works.",
    "The design side is where I have spent the last three years building real depth. I have done 0 to 1 product work at Accolade, reducing lead management steps by 68%. I have worked at scale at MakeMyTrip redesigning booking flows used by millions of people.",
    "What ties all of it together is that I treat research as the foundation of every design decision I make. I understand the problem well enough to defend every choice. The technical background helps me build faster and collaborate better. The design practice is where I do my best thinking.",
    "Outside of work, I enjoy experimenting at the intersection of design, technology, and Generative AI. I build side projects like AI-powered photo booths, journaling jars, and personal library apps, and I code interactive UI prototypes using real data. I also mentor 30+ students as an ADPList Campus Leader and was the First Runner-Up at the Claude Hackathon 2026.",
  ],
  portrait: {
    src: "/images/about/portrait.png",
    alt: "Ananya at a design showcase",
  },
  stats: [
    { id: "AboutStatProjects", value: 20, suffix: "+", label: "Projects Delivered" },
    { id: "AboutStatIndustry", value: 6, suffix: "+", label: "Industry" },
    { id: "AboutStatScreens", value: 200, suffix: "+", label: "Screens Designed" },
  ],
  contactCta: {
    label: "Contact Me",
    href: "https://calendar.app.google/mKqHKMBfxw5HDBRZ7",
  },
  interestsTitle: "What I'm into right now",
  interests: [
    "AI tools",
    "Minimal interfaces",
    "Street photography",
    "Design systems",
    "Frappuccino",
    "Long walks",
    "Ramen",
    "Sketching in coffee shops",
    "Starbucks",
    "Ambient music",
    "Room Aesthetics",
  ],
  valuesTitle: "The values behind my work",
  values: [
    {
      id: "AboutValueCourage",
      title: "Courage",
      body: "I take initiative, explore new ideas, and make decisions even when the path isn’t clear.",
    },
    {
      id: "AboutValueAdaptability",
      title: "Adaptability",
      body: "I stay flexible, learn quickly, and adjust to challenges without losing direction or focus.",
    },
    {
      id: "AboutValueHonesty",
      title: "Honesty",
      body: "I communicate openly, give feedback, and focus on what truly matters for the outcome.",
    },
    {
      id: "AboutValueTeamwork",
      title: "Teamwork",
      body: "I love collaborating, ownership, and believe the best results come from teamwork.",
    },
  ],
  behindTitle: "Behind the scene meet the designer",
  behindTheScenes: [
    { src: "/images/about/portrait.png", alt: "Capstone showcase" },
    { src: "/images/about/bts-1.jpeg", alt: "Behind the scenes portrait" },
    { src: "/images/about/bts-2.jpg", alt: "Quiet studio light" },
    { src: "/images/about/bts-3.jpeg", alt: "Travel still" },
    { src: "/images/about/bts-4.png", alt: "Studio moment" },
    { src: "/images/about/bts-5.png", alt: "Candid frame" },
    { src: "/images/about/book-8.jpg", alt: "A day out" },
    { src: "/images/about/polaroid-1.jpeg", alt: "Working on a flow" },
    { src: "/images/about/polaroid-6.jpeg", alt: "Polaroid six" },
    { src: "/images/about/polaroid-4.jpeg", alt: "Polaroid four" },
  ],
  booksTitle: "Books I keep coming back to",
  books: [
    { src: "/images/about/book-1.jpg", alt: "Thinking in Systems by Donella H. Meadows" },
    { src: "/images/about/book-5.jpg", alt: "Grid systems in graphic design by Josef Müller-Brockmann" },
    { src: "/images/about/book-2.jpg", alt: "Design book" },
    { src: "/images/about/book-3.jpg", alt: "Design book" },
    { src: "/images/about/book-4.jpg", alt: "Design book" },
    { src: "/images/about/book-6.jpeg", alt: "Design book" },
    { src: "/images/about/book-7.jpg", alt: "Design book" },
  ],
} as const;
